#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpthread-stubs
Version  : 0.4
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/xcb/libpthread-stubs-0.4.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/xcb/libpthread-stubs-0.4.tar.bz2
Summary  : Meta package for pthread symbols - defaults to heavyweight ones if the C runtime does not provide lightweight ones.
Group    : Development/Tools
License  : MIT-feh
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
Project description
-------------------
Currently the project provides only a pkg-config [.pc] file, pthread-stubs.pc.
The latter contains the Cflags/Libs flags applicable to programs/libraries
that use only lightweight pthread API. See the next sections for the reasoning
and implementation details.

%package dev
Summary: dev components for the libpthread-stubs package.
Group: Development
Provides: libpthread-stubs-devel

%description dev
dev components for the libpthread-stubs package.


%package dev32
Summary: dev32 components for the libpthread-stubs package.
Group: Default
Requires: libpthread-stubs-dev

%description dev32
dev32 components for the libpthread-stubs package.


%prep
%setup -q -n libpthread-stubs-0.4
pushd ..
cp -a libpthread-stubs-0.4 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489677219
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1489677219
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/pthread-stubs.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32pthread-stubs.pc
/usr/lib32/pkgconfig/pthread-stubs.pc
